// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPhMPXehorNqFlJb5QfTz4IKhp8-1grm0',
    appId: '1:553666661056:web:7075f8e42afb944bb9fb25',
    messagingSenderId: '553666661056',
    projectId: 'appday-3a145',
    authDomain: 'appday-3a145.firebaseapp.com',
    storageBucket: 'appday-3a145.appspot.com',
    measurementId: 'G-WPGE7YJE4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc--pCR8hHt_66-EfG5sR7DdaIuycXdK4',
    appId: '1:553666661056:android:b657da9cd00bf8f2b9fb25',
    messagingSenderId: '553666661056',
    projectId: 'appday-3a145',
    storageBucket: 'appday-3a145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZPvXPh7sldsdUo4e5wb6V_Ttxx7pygI',
    appId: '1:553666661056:ios:18a611386aee8e4fb9fb25',
    messagingSenderId: '553666661056',
    projectId: 'appday-3a145',
    storageBucket: 'appday-3a145.appspot.com',
    iosClientId: '553666661056-tl3jhqruakfrer1c1oio8rllnovh8nb2.apps.googleusercontent.com',
    iosBundleId: 'com.ashish.appday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZPvXPh7sldsdUo4e5wb6V_Ttxx7pygI',
    appId: '1:553666661056:ios:18a611386aee8e4fb9fb25',
    messagingSenderId: '553666661056',
    projectId: 'appday-3a145',
    storageBucket: 'appday-3a145.appspot.com',
    iosClientId: '553666661056-tl3jhqruakfrer1c1oio8rllnovh8nb2.apps.googleusercontent.com',
    iosBundleId: 'com.ashish.appday',
  );
}
